---
- name: Gather package facts
  package_facts:
    manager: auto
  changed_when: false
  tags:
    - always

- name: List users accounts
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: false
  tags:
    - always

- name: Find privileged binary
  command: "find {{ item }} -xdev \\( -perm -4000 -o -perm -2000 \\) -type f"
  register: priv_binaries
  changed_when: false
  with_items: "{{ cis_rhel8_priv_partitions }}"
  tags:
    - always
